---
title: "Concentración Diaria 2020"
author: "Ierse-Universidad del Azuay"
date: "3/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = "C:/Users/Ale/Documents/R", echo = FALSE)
```

### Análisis del Comportamiento diario de las variables atmosféricas PM2.5 Y SO2 durante los meses de enero a noviembre 2020


```{r librerias ,error=FALSE,message=FALSE,echo=FALSE}
library("datetime")
library("date")
library("dplyr")
library("magrittr")
library("DataExplorer")
library("csv")  
library("lubridate")
library("tidyverse")
library("nycflights13")
library("tidyverse")
library("lubridate")
library("datos")
library("xts")
library("zoo")
library("PerformanceAnalytics")
options(dplyr.summarise.inform = FALSE)

```

```{r datos, echo=FALSE}
color<-c("grey","gold");
limitey=c(0, 200)


```

```{r datosFaltantes, echo=FALSE}
datos <- read.csv("C:/Users/Ale/Documents/R/PromediosDiariosPorContaminantes2020.csv", sep=";", header=TRUE)

```


```{r formatearDatos , echo=FALSE}

datos <- datos[!is.na(datos$PM2_5.Maximo),]
datosSO2<-data.frame(datos$Fecha,datos$PM2_5.Maximo)
colnames(datosSO2)<-c("fecha","pm2.5")

```

```{r cambioSeperadosDatos, echo=FALSE}
datosSO2$pm2.5 <- sub(",", ".", datosSO2$pm2.5, fixed = TRUE)  

datosSO2$pm2.5<- as.numeric(datosSO2$pm2.5)
datosSO2$fecha=as.Date(datosSO2$fecha,'%d/%m/%Y')


promediopm2.5=mean(datosSO2$pm2.5)

OMSpm2.5=25

fecha=as.Date('11/07/2020','%d/%m/%Y')

newdata <- subset(datosSO2, pm2.5 >= OMSpm2.5, "pm2.5")


porcentajepm2.5=(100*nrow(newdata))/nrow(datos)


```


```{r graficoContracionPM2 , echo=FALSE, warning=FALSE}

OMS=25
ggplot(data=datosSO2, aes(x=fecha, y=(pm2.5) )) + 
  geom_bar(stat="identity", position=position_dodge(), aes(fill = pm2.5 > OMS))  +
  xlab("2020")+ # eje x
  ylab("ug/m3")+ # eje y
  scale_y_continuous(limits = limitey)+
  scale_fill_manual(values = color,name="", labels=c("PM2.5<25 ug/m3","PM2.5>25 ug/m3") )+
  labs(title = "Concentración PM2.5 diario máximo 2020",
       subtitle = "01/01/2020 - 31/11/2020", 
       caption = "El 42.52% de los datos están por encima de la norma OMS
       IERSE-Universidad del Azuay") +# t?tulo de legenda+
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle= element_text(hjust = 0.5))


```


```{r graficoContracionPM25 , echo=FALSE, warning=FALSE}

p1<-ggplot(data=datosSO2, aes(x=fecha, y=(pm2.5) )) + 
  geom_bar(stat="identity", position=position_dodge())  +
  xlab("2020")+ # eje x
  ylab("ug/m3")+ # eje y
  scale_fill_manual(values = color )+
  scale_y_continuous(limits = limitey)+
  labs(title = "Concentración PM2.5 diario máximo 2020",
       subtitle = "01/01/2020 - 31/11/2020", 
       caption = "IERSE-Universidad del Azuay") +
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle= element_text(hjust = 0.5))

p1 + geom_hline(aes(yintercept=promediopm2.5), colour="yellow3", linetype="solid")+ 
  geom_hline(aes(yintercept=OMSpm2.5), colour="red", linetype="solid")+ 
  annotate("text", x=fecha-15, y=180, label="- OMS 25 ug/m3", color="red",size=3.5)+
  annotate("text", x=fecha-15, y=190, label="- PROM 25.85 ug/m3", color="yellow3",size=3.5)

```

```{r leerDatosSO2 , echo=FALSE}
datos <- read.csv("C:/Users/Ale/Documents/R/PromediosDiariosPorContaminantes2020.csv", sep=";", header=TRUE)

```


```{r formatearDatosSO2 , echo=FALSE}

datos <- datos[!is.na(datos$SO2.Maximo),]
datosso2<-data.frame(datos$Fecha,datos$SO2.Maximo)
colnames(datosso2)<-c("fecha","so2")  
```

```{r cambioSeperadosDatosSO2, echo=FALSE}
datosso2$so2 <- sub(",", ".", datosso2$so2, fixed = TRUE) 

datosso2$so2<- as.numeric(datosso2$so2)
datosso2$fecha=as.Date(datosso2$fecha,'%d/%m/%Y')

promedioso2=mean(datosso2$so2)

OMS=20 
OMSso2=20
normaSo2Ecua=200

fechaso2=as.Date('11/06/2020','%d/%m/%Y')
newdata <- subset(datosso2, so2 >= OMS, "so2")
porcentaje20=(100*nrow(newdata))/nrow(datosso2)


```


```{r graficoContracionSO2 , echo=FALSE, warning=FALSE}
OMS=20 

ggplot(data=datosso2, aes(x=fecha, y=(so2) )) + 
  geom_bar(stat="identity", position=position_dodge(), aes(fill = so2 > OMS))  +
  xlab("2020")+ # eje x
  ylab("ug/m3")+ # eje y
  scale_fill_manual(values = color,name="", labels=c("SO2<20 ug/m3","SO2>20 ug/m3") )+
  scale_y_continuous(limits = limitey)+
  scale_x_date(date_labels = "%b")+
  labs(title = "Concentración SO2 diario máximo 2020",
       subtitle = "01/01/2020 - 30/11/2020", 
       caption = "El 83.99% de los registros están por encima de la norma OMS
       
       IERSE-Universidad del Azuay") +
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle= element_text(hjust = 0.5))

```


```{r graficoContracionSO22 , echo=FALSE, warning=FALSE}
p1<-ggplot(data=datosso2, aes(x=fecha, y=(so2) )) + 
  geom_bar(stat="identity", position=position_dodge(), )  +
  xlab("2020")+ # eje x
  ylab("ug/m3")+ # eje y
  scale_fill_manual(values = color)+
  scale_y_continuous(limits = limitey)+
  labs(title = "Concentración SO2 diario máximo 2020",
       subtitle = "01/01/2020 - 31/11/2020", 
       caption = "IERSE-Universidad del Azuay") +
  theme(plot.title = element_text(hjust = 0.5),plot.subtitle= element_text(hjust = 0.5))

p1 + geom_hline(aes(yintercept=promedioso2), colour="yellow3", linetype="solid")+ 
  geom_hline(aes(yintercept=OMSso2), colour="red", linetype="solid")+ 
  geom_hline(aes(yintercept=normaSo2Ecua), colour="blue", linetype="solid")+ 
  annotate("text", x=fechaso2+15, y=170, label="- OMS 20 ug/m3", color="red",size=3.5)+
  annotate("text", x=fechaso2+15, y=180, label="- PROM 42.10 ug/m3", color="yellow3",size=3.5)+
  annotate("text", x=fechaso2+15, y=190, label="- TULSMA 200 ug/m3", color="blue",size=3.5)

```

